language: python

install:
  - pip install tox coveralls

script: tox

env:
  - PEEWEE_TEST_BACKEND=sqlite
  - PEEWEE_TEST_BACKEND=postgresql
  - PEEWEE_TEST_BACKEND=mysql

services:
  - postgres
  - mysql

notifications:
  email: false

before_script:
  - sh -c "make setup_databases"


after_success:
  - coveralls

cache: pip

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
