version: '3'

services:
  peewee_extras:
    build: .
    command: make test
    volumes:
      - ./:/app
    environment:
      MYSQL_URI: mysql://root:root@mysql:3306/test

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

